//example button jest test case generated by chatgpt
// Button.test.jsx
import { render, screen, fireEvent } from "@testing-library/react";
import Button from "./Button";

describe("Button component", () => {
  test("renders with correct label", () => {
	render(<Button label="Click Me" />);
	expect(screen.getByText("Click Me")).toBeInTheDocument();
  });

  test("calls handler when clicked", () => {
	const handleClick = vi.fn();
	render(<Button label="Press" onClick={handleClick} />);
	fireEvent.click(screen.getByText("Press"));
	expect(handleClick).toHaveBeenCalledTimes(1);
  });

  test("renders as disabled when prop is true", () => {
	render(<Button label="Can't click" disabled />);
	expect(screen.getByRole("button")).toBeDisabled();
  });
});
